"""postgresql_initial_migration

Revision ID: 1a2b3c4d5e6f
Revises: 
Create Date: 2026-02-23 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1a2b3c4d5e6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create alembic version table
    op.create_table('alembic_version',
        sa.Column('version_num', sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint('version_num')
    )
    
    # Create users table
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=255), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('hashed_password', sa.String(length=255), nullable=False),
        sa.Column('role', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('organization_id', sa.Integer(), nullable=True),
        sa.Column('manager_id', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index('idx_users_organization_id', 'users', ['organization_id'], unique=False)
    op.create_index('idx_users_manager_id', 'users', ['manager_id'], unique=False)
    
    # Create organizations table
    op.create_table('organizations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('owner_id', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('is_public', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.create_index('idx_organizations_owner_id', 'organizations', ['owner_id'], unique=False)
    
    # Create tags table
    op.create_table('tags',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('color', sa.String(length=20), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tags_name', 'tags', ['name'], unique=True)
    op.create_index('idx_tag_name', 'tags', ['name'], unique=False)
    
    # Create categories table
    op.create_table('categories',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('code', sa.String(length=50), nullable=True),
        sa.Column('organization_id', sa.Integer(), nullable=True),
        sa.Column('parent_id', sa.Integer(), nullable=True),
        sa.Column('level', sa.Integer(), nullable=True),
        sa.Column('path', sa.String(length=500), nullable=True),
        sa.Column('sort_order', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index('idx_categories_organization_id', 'categories', ['organization_id'], unique=False)
    op.create_index('idx_categories_parent_id', 'categories', ['parent_id'], unique=False)
    op.create_index('idx_categories_created_by', 'categories', ['created_by'], unique=False)
    
    # Create departments table
    op.create_table('departments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('code', sa.String(length=50), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('organization_id', sa.Integer(), nullable=False),
        sa.Column('parent_id', sa.Integer(), nullable=True),
        sa.Column('level', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_index('idx_departments_organization_id', 'departments', ['organization_id'], unique=False)
    op.create_index('idx_departments_parent_id', 'departments', ['parent_id'], unique=False)
    
    # Create questions table
    op.create_table('questions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('text', sa.Text(), nullable=False),
        sa.Column('type', sa.String(length=20), nullable=False),
        sa.Column('options', sa.Text(), nullable=True),
        sa.Column('is_required', sa.Boolean(), nullable=True),
        sa.Column('order', sa.Integer(), nullable=True),
        sa.Column('owner_id', sa.Integer(), nullable=True),
        sa.Column('organization_id', sa.Integer(), nullable=True),
        sa.Column('category_id', sa.Integer(), nullable=True),
        sa.Column('usage_count', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('min_score', sa.Integer(), nullable=True),
        sa.Column('max_score', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_index('idx_questions_owner_id', 'questions', ['owner_id'], unique=False)
    op.create_index('idx_questions_organization_id', 'questions', ['organization_id'], unique=False)
    op.create_index('idx_questions_category_id', 'questions', ['category_id'], unique=False)
    
    # Create surveys table
    op.create_table('surveys',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_by_user_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('organization_id', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surveys_id'), 'surveys', ['id'], unique=False)
    op.create_index(op.f('ix_surveys_title'), 'surveys', ['title'], unique=False)
    op.create_index('idx_surveys_created_by_user_id', 'surveys', ['created_by_user_id'], unique=False)
    op.create_index('idx_surveys_organization_id', 'surveys', ['organization_id'], unique=False)
    
    # Create participants table
    op.create_table('participants',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('department_id', sa.Integer(), nullable=True),
        sa.Column('position', sa.String(length=255), nullable=True),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('phone', sa.String(length=50), nullable=True),
        sa.Column('organization_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participants_id'), 'participants', ['id'], unique=False)
    op.create_index('idx_participants_department_id', 'participants', ['department_id'], unique=False)
    op.create_index('idx_participants_organization_id', 'participants', ['organization_id'], unique=False)
    
    # Create organization_members table
    op.create_table('organization_members',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('organization_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('role', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('organization_id', 'user_id', name='_organization_user_uc')
    )
    op.create_index(op.f('ix_organization_members_id'), 'organization_members', ['id'], unique=False)
    op.create_index('idx_organization_members_organization_id', 'organization_members', ['organization_id'], unique=False)
    op.create_index('idx_organization_members_user_id', 'organization_members', ['user_id'], unique=False)
    
    # Create question_tags table (many-to-many relationship)
    op.create_table('question_tags',
        sa.Column('question_id', sa.Integer(), nullable=False),
        sa.Column('tag_id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('question_id', 'tag_id')
    )
    op.create_index('idx_question_tags_question_id', 'question_tags', ['question_id'], unique=False)
    op.create_index('idx_question_tags_tag_id', 'question_tags', ['tag_id'], unique=False)
    
    # Create survey_questions table
    op.create_table('survey_questions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('survey_id', sa.Integer(), nullable=False),
        sa.Column('question_id', sa.Integer(), nullable=False),
        sa.Column('order', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_questions_id'), 'survey_questions', ['id'], unique=False)
    op.create_index('idx_survey_questions_survey_id', 'survey_questions', ['survey_id'], unique=False)
    op.create_index('idx_survey_questions_question_id', 'survey_questions', ['question_id'], unique=False)
    
    # Create survey_answers table
    op.create_table('survey_answers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('survey_id', sa.Integer(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('submitted_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('answers', sa.Text(), nullable=False),
        sa.Column('participant_id', sa.Integer(), nullable=True),
        sa.Column('total_score', sa.Integer(), nullable=True),
        sa.Column('department', sa.Text(), nullable=True),
        sa.Column('position', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_answers_id'), 'survey_answers', ['id'], unique=False)
    op.create_index('idx_survey_answers_survey_id', 'survey_answers', ['survey_id'], unique=False)
    op.create_index('idx_survey_answers_user_id', 'survey_answers', ['user_id'], unique=False)
    op.create_index('idx_survey_answers_participant_id', 'survey_answers', ['participant_id'], unique=False)
    
    # Add foreign key constraints
    op.create_foreign_key('fk_users_organization_id', 'users', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key('fk_users_manager_id', 'users', 'users', ['manager_id'], ['id'])
    op.create_foreign_key('fk_organizations_owner_id', 'organizations', 'users', ['owner_id'], ['id'])
    op.create_foreign_key('fk_organization_members_organization_id', 'organization_members', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key('fk_organization_members_user_id', 'organization_members', 'users', ['user_id'], ['id'])
    op.create_foreign_key('fk_departments_organization_id', 'departments', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key('fk_departments_parent_id', 'departments', 'departments', ['parent_id'], ['id'])
    op.create_foreign_key('fk_categories_organization_id', 'categories', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key('fk_categories_parent_id', 'categories', 'categories', ['parent_id'], ['id'])
    op.create_foreign_key('fk_categories_created_by', 'categories', 'users', ['created_by'], ['id'])
    op.create_foreign_key('fk_questions_owner_id', 'questions', 'users', ['owner_id'], ['id'])
    op.create_foreign_key('fk_questions_organization_id', 'questions', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key('fk_questions_category_id', 'questions', 'categories', ['category_id'], ['id'])
    op.create_foreign_key('fk_surveys_created_by_user_id', 'surveys', 'users', ['created_by_user_id'], ['id'])
    op.create_foreign_key('fk_surveys_organization_id', 'surveys', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key('fk_participants_department_id', 'participants', 'departments', ['department_id'], ['id'])
    op.create_foreign_key('fk_participants_organization_id', 'participants', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key('fk_question_tags_question_id', 'question_tags', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_question_tags_tag_id', 'question_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_survey_questions_survey_id', 'survey_questions', 'surveys', ['survey_id'], ['id'])
    op.create_foreign_key('fk_survey_questions_question_id', 'survey_questions', 'questions', ['question_id'], ['id'])
    op.create_foreign_key('fk_survey_answers_survey_id', 'survey_answers', 'surveys', ['survey_id'], ['id'])
    op.create_foreign_key('fk_survey_answers_user_id', 'survey_answers', 'users', ['user_id'], ['id'])
    op.create_foreign_key('fk_survey_answers_participant_id', 'survey_answers', 'participants', ['participant_id'], ['id'])
    
    # Insert initial alembic version
    op.execute("INSERT INTO alembic_version (version_num) VALUES ('1a2b3c4d5e6f')")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop all tables in reverse order
    op.drop_table('survey_answers')
    op.drop_table('survey_questions')
    op.drop_table('question_tags')
    op.drop_table('participants')
    op.drop_table('surveys')
    op.drop_table('questions')
    op.drop_table('departments')
    op.drop_table('categories')
    op.drop_table('tags')
    op.drop_table('organization_members')
    op.drop_table('organizations')
    op.drop_table('users')
    op.drop_table('alembic_version')
    
    # ### end Alembic commands ###