"""Add manager_id to users table

Revision ID: 8bd2a01d9ff8
Revises: 8c7e37fd06bc
Create Date: 2025-07-31 11:23:21.954064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8bd2a01d9ff8'
down_revision: Union[str, Sequence[str], None] = '8c7e37fd06bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.add_column('organizations', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('organizations', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.drop_constraint(op.f('organizations_ibfk_1'), 'organizations', type_='foreignkey')
    op.create_foreign_key(None, 'organizations', 'users', ['owner_id'], ['id'])
    op.drop_column('organizations', 'parent_id')
    op.add_column('surveys', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'surveys', 'organizations', ['organization_id'], ['id'])
    op.add_column('users', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('users_ibfk_2'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'users', ['manager_id'], ['id'])
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_ibfk_2'), 'users', 'users', ['user_id'], ['id'])
    op.drop_column('users', 'manager_id')
    op.drop_constraint(None, 'surveys', type_='foreignkey')
    op.drop_column('surveys', 'organization_id')
    op.add_column('organizations', sa.Column('parent_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.create_foreign_key(op.f('organizations_ibfk_1'), 'organizations', 'organizations', ['parent_id'], ['id'])
    op.drop_column('organizations', 'is_public')
    op.drop_column('organizations', 'is_active')
    op.drop_column('organizations', 'owner_id')
    # ### end Alembic commands ###
