"""Correct foreign key for user table

Revision ID: 8c7e37fd06bc
Revises: 5549ed82836e
Create Date: 2025-07-10 16:10:25.637204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8c7e37fd06bc'
down_revision: Union[str, Sequence[str], None] = '5549ed82836e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_options_id'), table_name='options')
    op.drop_table('options')
    op.drop_index(op.f('ix_answers_id'), table_name='answers')
    op.drop_table('answers')
    op.add_column('questions', sa.Column('type', sa.Enum('SINGLE_CHOICE', 'MULTI_CHOICE', 'TEXT_INPUT', 'NUMBER_INPUT', name='questiontype'), nullable=False))
    op.add_column('questions', sa.Column('options', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('is_required', sa.Boolean(), nullable=True))
    op.add_column('questions', sa.Column('order', sa.Integer(), nullable=True))
    op.alter_column('questions', 'text',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               nullable=False)
    op.alter_column('questions', 'survey_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('questions', 'question_type')
    op.add_column('users', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'user_id')
    op.add_column('questions', sa.Column('question_type', mysql.VARCHAR(length=50), nullable=False))
    op.alter_column('questions', 'survey_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('questions', 'text',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('questions', 'order')
    op.drop_column('questions', 'is_required')
    op.drop_column('questions', 'options')
    op.drop_column('questions', 'type')
    op.create_table('answers',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('question_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('answer_text', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('answers_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('answers_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_answers_id'), 'answers', ['id'], unique=False)
    op.create_table('options',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('option_text', mysql.TEXT(), nullable=False),
    sa.Column('option_value', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('options_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_options_id'), 'options', ['id'], unique=False)
    # ### end Alembic commands ###
