"""Make survey_id nullable in questions table

Revision ID: b368f69156a8
Revises: 8bd2a01d9ff8
Create Date: 2025-08-10 10:59:14.111269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b368f69156a8'
down_revision: Union[str, Sequence[str], None] = '8bd2a01d9ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'survey_id',
               existing_type=sa.Integer(),
               nullable=True) # <-- 改为 True
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'survey_id',
               existing_type=sa.Integer(),
               nullable=False) # <-- 回滚时改为 False
    # ### end Alembic commands ###
