"""add total_score department position to survey_answers

Revision ID: bbdef0aeda07
Revises: 3113bafe1c2a
Create Date: 2025-12-07 21:37:15.683613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bbdef0aeda07'
down_revision: Union[str, Sequence[str], None] = '3113bafe1c2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('idx_tag_name'), table_name='tags')
    # op.drop_index(op.f('name'), table_name='tags')
    # op.drop_table('tags')
    # op.drop_index(op.f('idx_question_tags_question_id'), table_name='question_tags')
    # op.drop_index(op.f('idx_question_tags_tag_id'), table_name='question_tags')
    # op.drop_table('question_tags')
    op.add_column('survey_answers', sa.Column('total_score', sa.Integer(), nullable=True))
    op.add_column('survey_answers', sa.Column('department', sa.Text(), nullable=True))
    op.add_column('survey_answers', sa.Column('position', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey_answers', 'position')
    op.drop_column('survey_answers', 'department')
    op.drop_column('survey_answers', 'total_score')
    # op.create_table('question_tags',
    # sa.Column('question_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('tag_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    # sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('question_tags_ibfk_1'), ondelete='CASCADE'),
    # sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('question_tags_ibfk_2'), ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('question_id', 'tag_id'),
    # mysql_collate='utf8mb4_0900_ai_ci',
    # mysql_default_charset='utf8mb4',
    # mysql_engine='InnoDB'
    # )
    # op.create_index(op.f('idx_question_tags_tag_id'), 'question_tags', ['tag_id'], unique=False)
    # op.create_index(op.f('idx_question_tags_question_id'), 'question_tags', ['question_id'], unique=False)
    # op.create_table('tags',
    # sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    # sa.Column('color', mysql.VARCHAR(length=20), server_default=sa.text("'#409EFF'"), nullable=True),
    # sa.Column('description', mysql.TEXT(), nullable=True),
    # sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    # sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    # sa.PrimaryKeyConstraint('id'),
    # mysql_collate='utf8mb4_0900_ai_ci',
    # mysql_default_charset='utf8mb4',
    # mysql_engine='InnoDB'
    # )
    # op.create_index(op.f('name'), 'tags', ['name'], unique=True)
    # op.create_index(op.f('idx_tag_name'), 'tags', ['name'], unique=False)
    # ### end Alembic commands ###
