"""Add questions relationship to User model

Revision ID: c129020b449a
Revises: b368f69156a8
Create Date: 2025-08-12 14:19:43.520076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c129020b449a'
down_revision: Union[str, Sequence[str], None] = 'b368f69156a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'questions', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'owner_id')
    # ### end Alembic commands ###
