"""add_status_to_surveys

Revision ID: 533eb2534c25
Revises: 15b575ce0d16
Create Date: 2025-08-20 16:26:13.828958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '533eb2534c25'
down_revision: Union[str, Sequence[str], None] = '15b575ce0d16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('status', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surveys', 'status')
    # ### end Alembic commands ###
