"""add usage_count to questions table

Revision ID: 15b575ce0d16
Revises: 23bd084b04a7
Create Date: 2025-08-20 15:13:25.903547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15b575ce0d16'
down_revision: Union[str, Sequence[str], None] = '23bd084b04a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('usage_count', sa.Integer(), nullable=True, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'usage_count')
    # ### end Alembic commands ###
