"""add_department_and_participant_models

Revision ID: 708e4cafe87f
Revises: 9ec33a992406
Create Date: 2025-08-17 23:51:52.974342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '708e4cafe87f'
down_revision: Union[str, Sequence[str], None] = '9ec33a992406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'questions', 'organizations', ['organization_id'], ['id'])
    op.add_column('survey_answers', sa.Column('participant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'survey_answers', 'participants', ['participant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'survey_answers', type_='foreignkey')
    op.drop_column('survey_answers', 'participant_id')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'organization_id')
    # ### end Alembic commands ###
