"""add_survey_question_table_and_remove_survey_id_from_questions

Revision ID: cefc2140f628
Revises: 533eb2534c25
Create Date: 2025-08-20 17:03:21.543001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cefc2140f628'
down_revision: Union[str, Sequence[str], None] = '533eb2534c25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('questions_ibfk_1'), 'questions', type_='foreignkey')
    op.drop_column('questions', 'survey_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('survey_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('questions_ibfk_1'), 'questions', 'surveys', ['survey_id'], ['id'])
    # ### end Alembic commands ###
